services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: db-rm566234
    networks:
      - app-network
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - db_data:/opt/oracle/oradata
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/$${ORACLE_PASSWORD}@localhost:1521/XEPDB1 > /dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 360s

  app:
    build: .
    container_name: app-java-rm566234
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${ORACLE_PASSWORD}
      APP_ENV: production

  app-dotnet:
    build: 
      context: ../HyDrata
      dockerfile: Dockerfile
    container_name: app-csharp-rm566234
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__OracleConnection: "Data Source=oracle-db:1521/XEPDB1;User Id=system;Password=${ORACLE_PASSWORD:-oracle};"
      ASPNETCORE_ENVIRONMENT: "Production"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    name: db_data
